name: Android CI
on:
  push:
    paths:
      - '*.gradle.kts'
      - '*.properties'
      - app/**
  pull_request:
    paths:
      - '*.gradle.kts'
      - '*.properties'
      - app/**

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Build with Gradle
        run: ./gradlew clean assembleDebug
